// Generate scripts/seed-demo.sql: coherent demo fixtures for local dev — one pool,
// one open bid position with 24h of snapshots, and 6h of 1m candles following a
// deterministic price walk. Run: node scripts/gen-seed.mjs [ownerAddress]
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OWNER = process.argv[2] ?? "0xEA41b6d65d74742CbF52c29e200e5aE9fAe73058";
const POOL_ID = "0xdemo000000000000000000000000000000000000000000000000000000000001";
const CASHCAT = "0x020bfC650A365f8BB26819deAAbF3E21291018b4";
const WETH = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73";
const FRIAR = "0xFeDa24F0d3805170E7566cE617CfBa01cE05D080";

const E18 = 10n ** 18n;
const Q96 = 2n ** 96n;

// deterministic LCG so the demo data is stable across regenerations
let seed = 42;
const rand = () => (seed = (seed * 1103515245 + 12345) % 2 ** 31) / 2 ** 31;

// sqrtPriceX96 for a price expressed as 1e18-scale token1/token0
const sqrtFromPrice1e18 = (p) => {
  // sqrt(p/1e18) * 2^96 — do it in float then trim to bigint (demo precision is fine)
  const f = Math.sqrt(Number(p) / 1e18);
  return BigInt(Math.round(f * 2 ** 48)) * 2n ** 48n; // split exponent to stay in float range
};

const now = Math.floor(Date.now() / 1000);
const lines = [
  "-- generated by scripts/gen-seed.mjs — demo fixtures for local dev, DO NOT deploy remotely",
  `DELETE FROM pools WHERE pool_id = '${POOL_ID}';`,
  `DELETE FROM positions WHERE position_id = 9001;`,
  `DELETE FROM position_bins WHERE position_id = 9001;`,
  `DELETE FROM snapshots WHERE position_id = 9001;`,
  `DELETE FROM candles WHERE pool_id = '${POOL_ID}';`,
  `INSERT INTO pools (pool_id, currency0, currency1, fee, tick_spacing, hooks, watched) VALUES ('${POOL_ID}', '${CASHCAT}', '${WETH}', 8388608, 100, '${FRIAR}', 0);`,
];

// --- position: paid 1 WETH into a 5-bin bid ladder ---
lines.push(
  `INSERT INTO positions (position_id, owner, pool_id, opened_block, opened_ts, open_delta0, open_delta1, flow0, flow1, fees0, fees1, perf0, perf1) VALUES ` +
    `(9001, '${OWNER}', '${POOL_ID}', 1000000, ${now - 86_400}, '0', '-${E18}', '0', '0', '0', '${E18 / 50n}', '0', '${E18 / 500n}');`,
);
for (let i = 0; i < 5; i++) {
  lines.push(
    `INSERT INTO position_bins (position_id, bin_index, tick_lower, tick_upper, liquidity) VALUES (9001, ${i}, ${-100 * (i + 1)}, ${-100 * i}, '${(2n + BigInt(i)) * 10n ** 20n}');`,
  );
}

// --- 24h of snapshots every 5 min: price drifts down into the ladder, fees grow ---
let price = E18; // 1.0 token1 per token0, 1e18-scale
for (let t = now - 86_400; t <= now; t += 300) {
  const drift = 1 + (rand() - 0.53) * 0.004; // slight downward bias
  price = BigInt(Math.max(0.90e18, Math.min(1.05e18, Number(price) * drift)));
  const progress = (t - (now - 86_400)) / 86_400;
  const filled = Math.max(0, Math.min(1, (1e18 - Number(price)) / 0.06e18)); // deeper price = more filled
  const amount1 = BigInt(Math.round((1 - filled * 0.55) * 1e18));
  const amount0 = BigInt(Math.round(filled * 0.55 * 1e18)); // bought token, roughly value-neutral
  const fees1 = BigInt(Math.round(progress * 0.02e18)); // fee income accrues with time
  const sqrt = sqrtFromPrice1e18(price);
  lines.push(
    `INSERT INTO snapshots (position_id, ts, sqrt_price, market_sqrt_price, amount0, amount1, fees0, fees1) VALUES ` +
      `(9001, ${t}, '${sqrt}', NULL, '${amount0}', '${amount1}', '0', '${fees1}');`,
  );
}

// --- 6h of 1m candles on the demo pool ---
let c = E18;
for (let t = now - 6 * 3600; t <= now; t += 60) {
  const o = c;
  const moves = [rand(), rand(), rand()].map((r) => 1 + (r - 0.5) * 0.006);
  const a = BigInt(Math.round(Number(o) * moves[0]));
  const b = BigInt(Math.round(Number(a) * moves[1]));
  c = BigInt(Math.round(Number(b) * moves[2]));
  const hi = [o, a, b, c].reduce((x, y) => (y > x ? y : x));
  const lo = [o, a, b, c].reduce((x, y) => (y < x ? y : x));
  const vol1 = BigInt(Math.round(rand() * 3e18));
  const vol0 = (vol1 * E18) / c;
  lines.push(
    `INSERT INTO candles (pool_id, ts, open, high, low, close, vol0, vol1, swaps) VALUES ` +
      `('${POOL_ID}', ${t}, '${o}', '${hi}', '${lo}', '${c}', '${vol0}', '${vol1}', ${1 + Math.floor(rand() * 8)});`,
  );
}

const dest = join(dirname(fileURLToPath(import.meta.url)), "seed-demo.sql");
writeFileSync(dest, lines.join("\n") + "\n");
console.log(`wrote ${lines.length} statements -> ${dest} (owner ${OWNER})`);
